### ISSUE TITLE
Uso do método Meli::refreshTokenExpireIn

### ISSUE THREAD

**Issue by luiseduardobraschi** [wandesnet/mercado-livre#2]
Olá.

Estou muito interessado em usar esta lib, porém não está muito claro pra mim o uso do método `Meli::refreshTokenExpireIn`. 
Ele é chamado por alguma dependência?
Teria alguma exemplo de implementação?

Obrigado.

**Comment by luiseduardobraschi** [comment]
Nenhuma busca no GitHub ou usando recurso do Sublime de ver as chamadas de métodos mostrou que que o método é chamado no construtor da classe `MeliConnector`.

De toda forma, parabéns pela lib. Vai me ser muito útil.

**Comment by wandesnet** [comment]
Opa, @luiseduardobraschi, respondendo sua dúvida sobre o método `refreshTokenExpireIn()`.

Este método é responsável por atualizar o token quando estiver expirado. É crucial implementar sua lógica de armazenamento dos tokens para garantir o funcionamento adequado da autenticação.

```php
protected function refreshTokenExpireIn(): void
{
    if ($this->hasExpired()) {
        // Chamada para atualizar o token de acesso
        $refresh = $this->refreshAccessToken($this->refresh_token);

        // Atualizando os tokens e o tempo de expiração
        $this->access_token = $refresh->getAccessToken();
        $this->refresh_token = $refresh->getRefreshToken();
        $this->expires_in = $refresh->getExpiresAt()->getTimestamp();

        // Salvando os tokens atualizados, caso esteja utilizando Laravel, veja o exemplo abaixo:
        User::query()->find(1)->update([
            'access_token' => $this->access_token,
            'refresh_token' => $this->refresh_token,
            'expires_in' => $this->expires_in
        ]);
    }
}
```

Neste trecho de código, a condição if ($this->hasExpired()) verifica se o token atual está expirado. Se estiver, o método refreshAccessToken() é chamado para obter um novo token de acesso. Os tokens atualizados são então armazenados nas variáveis adequadas ($this->access_token e $this->refresh_token) e o tempo de expiração é atualizado para refletir o novo tempo de expiração.


Agora podemos utilizar os tokens válidos. Caso esteja usando Laravel veja um exemplo de como obter os tokens salvos na tabela de usuários.

```php 

$user = User::query()->find(1)

$response = Meli::make($user->access_token, $user->refresh_token, $user->expires_in)->auth()->request()->order(123456789);

var_dump($response);

```

**Comment by luiseduardobraschi** [comment]
Obrigado, @wandesnet 

Porém agora meu problema é que, ao tentar criar um anúncio, eu recebo a seguinte resposta:

```
array(
   'message' => 'access_token.invalid',
   'error' => 'Invalid OAuth access token.',
   'status' => 403,
   'cause' => 
  array (
  ),
)
```
Os dados estão sendo passados corretamente, tanto que com outra lib ou com curl eu consigo.

Quer que eu abra outra issue?

**Comment by luiseduardobraschi** [comment]
Muito obrigado, @wandesnet 

Já estou conseguindo integrar.

**Comment by wandesnet** [comment]
Boa noite, o erro indica que os tokens são inválidos, portanto você precisa
obter um novo access_token válido. No readme do github eu explico como
gerar a url de autenticação do Mercado Livre, e também como obter o
access_token.

Qualquer dúvida estou à disposição. Abs

Em qua., 1 de mai. de 2024 às 14:24, Luis Braschi ***@***.***>
escreveu:

**Comment by luiseduardobraschi** [comment]
Sim. Eu havia seguido o readme, mas esqueci de um detalhe. 
O comentário já foi apagado.
